name: Rubocop

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Rubocop
    strategy:
      matrix:
        ruby:
          - '3.0.2'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rubocop -A
